stages:

  Test:
    actions:
    - type: shell
      command: echo "Running flow file...."

  Update:
    actions: 
    - type: liquibase
      command: status

    - type: liquibase
      command: update

endStage:
  actions:
  - type: liquibase
    command: history
